### ISSUE TITLE
Option for setting TreatMissingData

### ISSUE THREAD

**Issue by sveinhelge** [cdklabs/cdk-watchful#12]
Would like to see the ability to set TreatMissingData for alarms.

I some case I would like to set treatMissingData = cloudwatch.TreatMissingData.IGNORE
or NOT_BREACHING for my alarms.

Example:
`wf.watchScope(backEndStack, { dynamodb: false, apiGateway: true, lambda: true, alarmOptions: { treatMissingData: TreatMissingData.NOT_BREACHING }});`

**Comment by BenChaimberg** [comment]
do not close
