### ISSUE TITLE
Support for ECS/Fargate Applications

### ISSUE THREAD

**Issue by phaniram** [cdklabs/cdk-watchful#13]
It would be great to have support for ECS/Fargate Applications (Covering NLB, ECS/Fargate compute)

**Comment by seawatts** [comment]
@eladb do you have much context on how to put this together?

**Comment by rrrix** [comment]
I came here for this!

**Comment by eladb** [comment]
Any volunteers to pick this up?

**Comment by phaniram** [comment]
@eladb 
I can pick this up, is there a doc on what all it should constitute ? or a basic monitoring setup for all resources that makes up this application should be good for starter ?

**Comment by eladb** [comment]
@phaniram that would be amazing!

I am not sure about resources. There are a bunch of best practices out there. One source would be the AWS Console. There are a bunch of pre-canned dashboards for ECS/Fargate. Perhaps we can use those as inspiration for a CDK-managed one.

**Comment by pgarbe** [comment]
When it comes to alarms, have a look here: https://github.com/marbot-io/monitoring-jump-start

Also, some ECS related alarms can not be created from metrics but from CloudWatch events (see https://github.com/marbot-io/monitoring-jump-start/blob/master/marbot.yml#L1056-L1074).

**Comment by mark-ship-it** [comment]
Can this issue be closed now?

**Comment by BenChaimberg** [comment]
closed by #26
