### ISSUE TITLE
watchScope() should not watch cdk internal lambdas automatically

### ISSUE THREAD

**Issue by pgarbe** [cdklabs/cdk-watchful#4]
When I add `wf.watchScope(this);` to my stack, it generates alarms (and dashboard) also for lambdas which have been generated by other CDK constructs (e.g. log retention lambda). 
In my opinion this should not be the default, as I want to focus on alarms of my application and not some internals of the CDK.

**Comment by BenChaimberg** [comment]
Currently, there is no way for us to detect whether a resource has been created by the CDK framework library, a third-party library, or your own code. A possible workaround could be subclassing `WatchLambdaFunction` to skip certain functions based on their construct ID/path and subclassing `Watchful` to produce your subclass when `watchLambdaFunction` is called.
