### ISSUE TITLE
Watchful SQS integration

### ISSUE THREAD

**Issue by aws-ps-hobson** [cdklabs/cdk-watchful#47]
would be great if dead letter queue and other critical SQS metrics can be part of cdk-watchful

**Comment by andrealascola-docebo** [comment]
I am working on that, hope to open a pr soon with a draft version

**Comment by jorgensen-eric-PFG** [comment]
@andrealascola-docebo are you still working on this?

**Comment by BenChaimberg** [comment]
Keep open
