### ISSUE TITLE
Undefined billingMode resulting in empty dashboard

### ISSUE THREAD

**Issue by pawKer** [cdklabs/cdk-watchful#474]
Hello,

I have managed to create a Watchful dashboard for my DynamoDB table but the dashboard came up empty without any widgets. After some investigation it looks like the billingMode is undefined on `this.dynamoDBTable.node.defaultChild.billingMode` whereas it is populated in `this.dynamoDBTable.billingMode`.

Do I need to populate that somehow or am I not defining the table correctly?

```
constructor(scope: cdk.Stack, id: string, props?: dynamodb.TableProps) {
		super(scope, id);
		this.dynamoDBTable = new dynamodb.Table(this, id, {
			...props,
			partitionKey: { name: "partitionKey", type: dynamodb.AttributeType.STRING },
			sortKey: { name: "sortKey", type: dynamodb.AttributeType.STRING },
			encryption: ...,
			tableName: "tableName",
		});
                 this.watchful = new Watchful(this, "Watchful");
		this.watchful.watchDynamoTable("DynamoDB", this.dynamoDBTable);
}
```

**Comment by hamzaashfaq-10p** [comment]
I am facing the same issue.

**Comment by pawKer** [comment]
Hi @hamzaashfaq-10p, not really. I just built it without watchful by using the CloudWatch cdk constructs.
