### ISSUE TITLE
CDK v2 Support

### ISSUE THREAD

**Issue by eladb** [cdklabs/cdk-watchful#482]
Hi there, we would like to to use watchful with a project that targets the developer preview of CDK v2.0 ([construct-hub](https://github.com/cdklabs/construct-hub)), and I was wondering what would be the best way to support that.

I guess we could maintain a separate branch that targets v2 and see how forward merges work in terms of conflicts. Any thoughts?

**Comment by BenChaimberg** [comment]
@eladb is this still desired? I can spend some time on this if so
