### ISSUE TITLE
Single Dashboard for multiple stacks

### ISSUE THREAD

**Issue by corrjo** [cdklabs/cdk-watchful#567]
It would be great to have a single dashboard for a whole app. Right now it seems like if I pass a watchful instance from one stack to another I get a circular dependency 

```
      throw new Error(`'${target.node.path}' depends on '${this.node.path}' (${cycle.join(', ')}). Adding this dependency (${reason}) would create a cyclic reference.`);
            ^
Error: 'Stack1' depends on 'Stack2' (Stack1 -> Stack2/myLambda/Resource.Ref, Stack1 -> Stack2/myLambdalLambdaTimeoutAlarm/Resource.Arn). Adding this dependency (Stack2 -> Stack1/alarmTopic/Resource.Ref) would create a cyclic reference.
```

**Comment by BenChaimberg** [comment]
What is the particular action that you're taking that causes a cyclical dependency? Seems like you may be subscribing a resource in Stack2 to an alarm created by watchful?
